Add Checkout Prompt blocklist and allowlist for files and directories.
SimpsonGSD/P4EditVS pull request #10
Opened 2021-07-16 05:28 UTC by bellicapax

This feature is to allow users to opt-in to prompts on certain files and directories. In especially large projects with lots of header dependencies, you might want to warn yourself before accidentally editing and saving a file that will cause the compilation of hundreds or thousands of other files. These two lists are an attempt at preventing that by defining areas or files where it's not safe to tread.

2021-07-16 11:25 UTC, SimpsonGSD requested changes
Hi thanks for the pull request. 

Although this is quite a niche feature I would be happy to take the change if the following bits of code were made lighter. This code path can be potentially called for a lot of files at once and blocks Visual Studio while doing so, so it must be as light as possible.

`CheckoutPromptBlocklist` and `CheckoutPromptBlocklist` return new lists every time. I would rather these were cached and state that a restart is required for changing these settings.

Is it possible to avoid the O(n) algorithm in `IsInPathList` as this function will scale badly with a large list, can a HashSet be used? The same goes for `IsInDirectory`.

Thanks,
Scott.

2021-07-17 00:49 UTC, bellicapax commented
I did my best to make it performant. Let me know if you have better ideas/more requests.

2021-07-17 00:56 UTC, bellicapax commented
Ok. That last commit should really be it for now. Haha, keep thinking of one more thing when I think I'm done.

2021-07-23 12:38 UTC, SimpsonGSD commented
Thanks for those updates.

2021-07-28 13:54 UTC, merged